import { Response } from 'express';
import prisma from '../db';
import { AuthRequest } from '../middleware/auth';
import { logAuditEvent } from '../utils/auditLogger';

export async function searchCustomers(req: AuthRequest, res: Response): Promise<void> {
  try {
    const query = ((req.query.q as string) || '').trim();

    if (!query) {
      const recentCustomers = await prisma.customer.findMany({
        take: 15,
        orderBy: { updatedAt: 'desc' },
        include: {
          _count: {
            select: { tickets: true },
          },
        },
      });
      res.json({ success: true, customers: recentCustomers });
      return;
    }

    const customers = await prisma.customer.findMany({
      where: {
        OR: [
          { name: { contains: query } },
          { phone: { contains: query } },
          { email: { contains: query } },
          { company: { contains: query } },
        ],
      },
      take: 20,
      include: {
        _count: {
          select: { tickets: true },
        },
      },
      orderBy: { createdAt: 'desc' },
    });

    res.json({ success: true, customers });
  } catch (error: any) {
    res.status(500).json({ success: false, message: 'Customer search failed', error: error.message });
  }
}

export async function createCustomer(req: AuthRequest, res: Response): Promise<void> {
  try {
    const { name, email, phone, company, address, notes } = req.body;
    const cleanName = typeof name === 'string' ? name.trim() : '';
    const cleanPhone = typeof phone === 'string' ? phone.trim() : '';
    const cleanEmail = typeof email === 'string' ? email.trim().toLowerCase() : '';

    if (!cleanName || cleanName.length < 2 || /^\d+$/.test(cleanName)) {
      res.status(400).json({ success: false, message: 'Please enter a valid customer full name (at least 2 characters, not purely numeric).' });
      return;
    }

    if (!/^[0-9]{10}$/.test(cleanPhone)) {
      res.status(400).json({ success: false, message: 'Please enter a valid 10-digit mobile number.' });
      return;
    }

    if (cleanEmail && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(cleanEmail)) {
      res.status(400).json({ success: false, message: 'Please enter a valid email address.' });
      return;
    }

    // Check if phone or email already registered
    const existing = await prisma.customer.findFirst({
      where: {
        OR: [{ phone: cleanPhone }, ...(cleanEmail ? [{ email: cleanEmail }] : [])],
      },
    });

    if (existing) {
      res.status(409).json({
        success: false,
        message: 'A customer with this phone number or email already exists.',
        customer: existing,
      });
      return;
    }

    const customer = await prisma.customer.create({
      data: {
        name: cleanName,
        email: cleanEmail || `${cleanPhone}@autogenerated.com`,
        phone: cleanPhone,
        company: company ? String(company).trim() : null,
        address: address ? String(address).trim() : null,
        notes: notes ? String(notes).trim() : null,
      },
    });

    await logAuditEvent({
      userId: req.user?.userId,
      action: 'CUSTOMER_CREATED',
      entityType: 'Customer',
      entityId: customer.id,
      details: { name: customer.name, phone: customer.phone },
      req,
    });

    res.status(201).json({ success: true, customer });
  } catch (error: any) {
    res.status(500).json({ success: false, message: 'Failed to create customer', error: error.message });
  }
}

export async function getCustomerById(req: AuthRequest, res: Response): Promise<void> {
  try {
    const id = req.params.id as string;

    const customer = await prisma.customer.findUnique({
      where: { id },
      include: {
        tickets: {
          orderBy: { createdAt: 'desc' },
          include: {
            category: true,
            department: true,
            assignedAgent: {
              select: { id: true, fullName: true, email: true },
            },
            feedback: true,
          },
        },
      },
    });

    if (!customer) {
      res.status(404).json({ success: false, message: 'Customer not found' });
      return;
    }

    // Calculate customer metrics
    const tickets = (customer as any).tickets || [];
    const totalTickets = tickets.length;
    const openTickets = tickets.filter((t: any) => !['CLOSED', 'CANCELLED', 'RESOLVED'].includes(t.status)).length;
    const resolvedTickets = tickets.filter((t: any) => ['RESOLVED', 'CLOSED'].includes(t.status)).length;

    res.json({
      success: true,
      customer,
      stats: {
        totalTickets,
        openTickets,
        resolvedTickets,
      },
    });
  } catch (error: any) {
    res.status(500).json({ success: false, message: 'Failed to fetch customer profile', error: error.message });
  }
}
